source "alicloud-ecs" "autogenerated_1" {
  access_key         = "${var.alicloud_access_key}"
  secret_key         = "${var.alicloud_secret_key}"
  region             = "cn-hongkong"
  image_force_delete = "true"
  image_name         = "codepipe_demo"
  instance_type      = "ecs.t5-lc1m1.small"
  io_optimized       = "true"
  source_image       = "ubuntu_20_04_uefi_x64_20G_alibase_20220324.vhd"
  ssh_password       = "Test12345"
  ssh_username       = "root"
}

build {
  sources = ["source.alicloud-ecs.autogenerated_1"]
}

#build {
#  sources = ["source.alicloud-ecs.autogenerated_1"]
  #provisioner "shell" {
  #  inline = ["apt-get update -yy", "apt-get install openjdk-8-jdk tomcat8 -yy", "mkdir -p /var/lib/tomcat8/webapps/"]
  #}
  #provisioner "file" {
    #destination = "/var/lib/tomcat8/webapps/"
    #source      = "target/demo.war"
  #}
#}
